using UnityEngine;
using System.Collections;

/// <summary>
/// Quản lý việc cộng Kinh Nghiệm (EXP) và Tăng Cấp (Level Up) cho thú.
/// </summary>
public class LevelUpManager : MonoBehaviour
{
    private static LevelUpManager _instance;
    public static LevelUpManager Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindFirstObjectByType<LevelUpManager>();
                if (_instance == null)
                {
                    GameObject go = new GameObject("LevelUpManager_AutoGenerated");
                    _instance = go.AddComponent<LevelUpManager>();
                }
            }
            return _instance;
        }
    }

    private void Awake()
    {
        if (_instance != null && _instance != this)
        {
            Destroy(gameObject);
        }
        else
        {
            _instance = this;
            DontDestroyOnLoad(gameObject); // Để tồn tại xuyên suốt các Scene
        }
    }

    /// <summary>
    /// Cộng EXP cho một thú cụ thể và xử lý Level Up nếu đủ.
    /// </summary>
    public void AddExpToBeast(RuntimeBeastData beast, int expAmount)
    {
        if (beast == null) return;

        beast.currentExp += expAmount;
        Debug.Log($"[LevelUpManager] {beast.baseBeast.beastName} nhận được {expAmount} EXP. Hiện tại: {beast.currentExp}/{beast.GetExpToNextLevel()}");

        // Vòng lặp phòng trường hợp nhận được quá nhiều EXP, nhảy nhiều Level cùng lúc
        while (true)
        {
            int requiredExpForCurrentLevel = beast.GetExpToNextLevel();
            if (beast.currentExp >= requiredExpForCurrentLevel)
            {
                beast.currentExp -= requiredExpForCurrentLevel;
                LevelUp(beast);
            }
            else
            {
                break;
            }
        }
    }

    /// <summary>
    /// Logic Tăng Cấp: Tăng cấp và kiểm tra xem có chiêu mới nào cần học không.
    /// </summary>
    private void LevelUp(RuntimeBeastData beast)
    {
        beast.currentLevel++;

        Debug.Log($"<color=yellow>[LevelUpManager] CHÚC MỪNG! {beast.baseBeast.beastName} đã thăng cấp lên Level {beast.currentLevel}!</color>");
        
        // Cập nhật nhiệm vụ tăng cấp
        if (global::QuestManager.Instance != null)
        {
            global::QuestManager.Instance.OnBeastLevelUp();
        }

        // ── Kiểm tra chiêu mới theo level ────────────────────────────────────
        CheckLearnableMoves(beast, beast.currentLevel);

        // ── Kiểm tra tiến hóa tự động theo level ──────────────────────────────
        CheckEvolution(beast);
    }

    private void CheckEvolution(RuntimeBeastData beast)
    {
        if (beast?.baseBeast == null) return;

        if (beast.baseBeast.evolveTarget != null && beast.baseBeast.evolveLevel > 0 && beast.currentLevel >= beast.baseBeast.evolveLevel)
        {
            EvolutionQueue.Enqueue(beast, beast.baseBeast.evolveTarget);
            Debug.Log($"<color=cyan>[LevelUpManager] {beast.baseBeast.beastName} đã đủ điều kiện tiến hóa thành {beast.baseBeast.evolveTarget.beastName} (Lv.{beast.currentLevel}/{beast.baseBeast.evolveLevel})!</color>");
        }
    }

    /// <summary>
    /// Kiểm tra bảng learnableMoves của Beast: nếu có chiêu cần học ở level này
    /// thì đưa vào LearnMoveQueue để xử lý sau trận (tránh gián đoạn flow trận đấu).
    /// </summary>
    private void CheckLearnableMoves(RuntimeBeastData beast, int newLevel)
    {
        if (beast?.baseBeast?.learnableMoves == null) return;

        foreach (var entry in beast.baseBeast.learnableMoves)
        {
            if (entry.move == null) continue;
            if (entry.levelRequired != newLevel) continue;

            // Đã có chiêu này rồi thì bỏ qua
            bool alreadyHas = false;
            if (beast.moves != null)
            {
                foreach (var m in beast.moves)
                {
                    if (m != null && m.baseMove == entry.move)
                    {
                        alreadyHas = true;
                        break;
                    }
                }
            }

            if (!alreadyHas)
            {
                LearnMoveQueue.Enqueue(beast, entry.move);
                Debug.Log($"[LevelUpManager] {beast.baseBeast.beastName} sắp học được chiêu mới: {entry.move.moveName} (Lv.{newLevel})");
            }
        }
    }

    /// <summary>
    /// Chia đều lượng EXP cho toàn bộ đội hình hiện tại của Player.
    /// Dùng sau khi thắng trận hoặc bắt được thú.
    /// </summary>
    public void DistributeExpToFormation(int totalExp, PlayerData playerData)
    {
        if (playerData == null || playerData.currentFormation == null) return;

        int beastCount = 0;
        foreach (var beast in playerData.currentFormation)
        {
            if (beast != null) beastCount++;
        }

        if (beastCount == 0) return;

        int expPerBeast = totalExp / beastCount; // Chia đều EXP

        foreach (var beast in playerData.currentFormation)
        {
            if (beast != null)
            {
                AddExpToBeast(beast, expPerBeast);
            }
        }
    }
}
