using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

/// <summary>
/// Quản lý Màn hình & Diễn hoạt Hoạt Ảnh Tiến Hóa (Evolution Cutscene)
/// Chuẩn phong cách Pokémon: Nhấp nháy, phát sáng bùng nổ, biến đổi thành dạng mới.
/// </summary>
public class EvolutionCutsceneManager : MonoBehaviour
{
    private static EvolutionCutsceneManager _instance;
    public static EvolutionCutsceneManager Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindFirstObjectByType<EvolutionCutsceneManager>();
                if (_instance == null)
                {
                    GameObject go = new GameObject("EvolutionCutsceneManager_AutoGenerated");
                    _instance = go.AddComponent<EvolutionCutsceneManager>();
                }
            }
            return _instance;
        }
    }

    [Header("UI Root Elements")]
    [SerializeField] private Canvas cutsceneCanvas;
    [SerializeField] private GameObject panelRoot;
    [SerializeField] private CanvasGroup panelCanvasGroup;

    [Header("Display Elements")]
    [SerializeField] private TextMeshProUGUI titleText;
    [SerializeField] private TextMeshProUGUI messageText;
    [SerializeField] private TextMeshProUGUI continuePromptText;
    [SerializeField] private Image beastImage;
    [SerializeField] private Image whiteSilhouetteImage;
    [SerializeField] private Image glowAuraImage;
    [SerializeField] private Image fullScreenFlash;
    [SerializeField] private Transform sparklesContainer;

    [Header("Audio (Tuỳ chọn)")]
    [SerializeField] private AudioSource audioSource;
    [SerializeField] private AudioClip evolvingMusic;
    [SerializeField] private AudioClip evolvedFanfare;

    private bool _isInitialized = false;
    private bool _isPlaying = false;
    public bool IsPlaying => _isPlaying;

    private void Awake()
    {
        if (_instance != null && _instance != this)
        {
            Destroy(gameObject);
            return;
        }

        _instance = this;
        DontDestroyOnLoad(gameObject);
        InitializeUI();
    }

    /// <summary>
    /// Tự động khởi tạo toàn bộ Canvas và UI nếu chưa được gán sẵn trong Inspector.
    /// </summary>
    private void InitializeUI()
    {
        if (_isInitialized) return;

        if (cutsceneCanvas == null)
        {
            cutsceneCanvas = gameObject.GetComponent<Canvas>();
            if (cutsceneCanvas == null)
            {
                cutsceneCanvas = gameObject.AddComponent<Canvas>();
                cutsceneCanvas.renderMode = RenderMode.ScreenSpaceOverlay;
                cutsceneCanvas.sortingOrder = 999; // Luôn hiển thị trên cùng mọi UI khác

                var scaler = gameObject.AddComponent<CanvasScaler>();
                scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
                scaler.referenceResolution = new Vector2(1920, 1080);
                scaler.matchWidthOrHeight = 0.5f;

                gameObject.AddComponent<GraphicRaycaster>();
            }
        }

        if (panelRoot == null)
        {
            BuildProceduralUI();
        }

        if (panelRoot != null)
        {
            panelRoot.SetActive(false);
        }

        _isInitialized = true;
    }

    /// <summary>
    /// Tự động dựng giao diện Cutscene chuẩn đẹp mắt
    /// </summary>
    private void BuildProceduralUI()
    {
        // 1. Panel nền tối
        panelRoot = new GameObject("EvolutionPanel");
        panelRoot.transform.SetParent(transform, false);
        var panelRect = panelRoot.AddComponent<RectTransform>();
        panelRect.anchorMin = Vector2.zero;
        panelRect.anchorMax = Vector2.one;
        panelRect.offsetMin = Vector2.zero;
        panelRect.offsetMax = Vector2.zero;

        var bgImage = panelRoot.AddComponent<Image>();
        bgImage.color = new Color(0.04f, 0.04f, 0.08f, 0.96f); // Nền tối huyền ảo
        panelCanvasGroup = panelRoot.AddComponent<CanvasGroup>();

        // 2. Title Text
        GameObject titleObj = new GameObject("TitleText");
        titleObj.transform.SetParent(panelRoot.transform, false);
        var titleRect = titleObj.AddComponent<RectTransform>();
        titleRect.anchorMin = new Vector2(0.1f, 0.78f);
        titleRect.anchorMax = new Vector2(0.9f, 0.92f);
        titleRect.offsetMin = Vector2.zero;
        titleRect.offsetMax = Vector2.zero;

        titleText = titleObj.AddComponent<TextMeshProUGUI>();
        titleText.alignment = TextAlignmentOptions.Center;
        titleText.fontSize = 42;
        titleText.fontStyle = FontStyles.Bold;
        titleText.color = new Color(1f, 0.95f, 0.6f); // Vàng ánh kim

        // 3. Center Container cho Beast
        GameObject centerObj = new GameObject("BeastCenter");
        centerObj.transform.SetParent(panelRoot.transform, false);
        var centerRect = centerObj.AddComponent<RectTransform>();
        centerRect.anchorMin = new Vector2(0.5f, 0.5f);
        centerRect.anchorMax = new Vector2(0.5f, 0.5f);
        centerRect.sizeDelta = new Vector2(320, 320);
        centerRect.anchoredPosition = new Vector2(0, 10);

        // 3a. Hào quang Aura
        GameObject auraObj = new GameObject("GlowAura");
        auraObj.transform.SetParent(centerObj.transform, false);
        var auraRect = auraObj.AddComponent<RectTransform>();
        auraRect.sizeDelta = new Vector2(480, 480);
        glowAuraImage = auraObj.AddComponent<Image>();
        glowAuraImage.color = new Color(0.4f, 0.8f, 1f, 0.35f);

        // 3b. Ảnh Beast chính
        GameObject imgObj = new GameObject("BeastImage");
        imgObj.transform.SetParent(centerObj.transform, false);
        var imgRect = imgObj.AddComponent<RectTransform>();
        imgRect.sizeDelta = new Vector2(280, 280);
        beastImage = imgObj.AddComponent<Image>();
        beastImage.preserveAspect = true;

        // 3c. Ảnh bóng trắng (White Silhouette) đè lên để nhấp nháy phát sáng
        GameObject silObj = new GameObject("WhiteSilhouette");
        silObj.transform.SetParent(centerObj.transform, false);
        var silRect = silObj.AddComponent<RectTransform>();
        silRect.sizeDelta = new Vector2(280, 280);
        whiteSilhouetteImage = silObj.AddComponent<Image>();
        whiteSilhouetteImage.preserveAspect = true;
        whiteSilhouetteImage.color = new Color(1f, 1f, 1f, 0f);

        // 3d. Container hạt phát sáng (Sparkles)
        GameObject sparkObj = new GameObject("SparklesContainer");
        sparkObj.transform.SetParent(centerObj.transform, false);
        sparklesContainer = sparkObj.transform;

        // 4. Message Text
        GameObject msgObj = new GameObject("MessageText");
        msgObj.transform.SetParent(panelRoot.transform, false);
        var msgRect = msgObj.AddComponent<RectTransform>();
        msgRect.anchorMin = new Vector2(0.1f, 0.18f);
        msgRect.anchorMax = new Vector2(0.9f, 0.32f);
        msgRect.offsetMin = Vector2.zero;
        msgRect.offsetMax = Vector2.zero;

        messageText = msgObj.AddComponent<TextMeshProUGUI>();
        messageText.alignment = TextAlignmentOptions.Center;
        messageText.fontSize = 36;
        messageText.color = Color.white;

        // 5. Prompt Text (Nhấn F để tiếp tục)
        GameObject promptObj = new GameObject("ContinuePrompt");
        promptObj.transform.SetParent(panelRoot.transform, false);
        var promptRect = promptObj.AddComponent<RectTransform>();
        promptRect.anchorMin = new Vector2(0.2f, 0.05f);
        promptRect.anchorMax = new Vector2(0.8f, 0.12f);
        promptRect.offsetMin = Vector2.zero;
        promptRect.offsetMax = Vector2.zero;

        continuePromptText = promptObj.AddComponent<TextMeshProUGUI>();
        continuePromptText.alignment = TextAlignmentOptions.Center;
        continuePromptText.fontSize = 24;
        continuePromptText.color = new Color(0.8f, 0.8f, 0.8f, 0.8f);
        continuePromptText.text = "Nhấn [F] hoặc Chuột để tiếp tục";

        // 6. Fullscreen Flash Overlay (Bùng sáng trắng chói lòa)
        GameObject flashObj = new GameObject("FullScreenFlash");
        flashObj.transform.SetParent(panelRoot.transform, false);
        var flashRect = flashObj.AddComponent<RectTransform>();
        flashRect.anchorMin = Vector2.zero;
        flashRect.anchorMax = Vector2.one;
        flashRect.offsetMin = Vector2.zero;
        flashRect.offsetMax = Vector2.zero;

        fullScreenFlash = flashObj.AddComponent<Image>();
        fullScreenFlash.color = new Color(1f, 1f, 1f, 0f);
        fullScreenFlash.raycastTarget = false;
    }

    /// <summary>
    /// Kích hoạt Cutscene tiến hóa cho một Beast cụ thể.
    /// </summary>
    public void PlayEvolution(RuntimeBeastData beast, BeastData targetForm, Action onComplete = null)
    {
        if (beast == null || targetForm == null)
        {
            onComplete?.Invoke();
            return;
        }

        InitializeUI();
        StartCoroutine(EvolutionRoutine(beast, targetForm, onComplete));
    }

    private IEnumerator EvolutionRoutine(RuntimeBeastData beast, BeastData targetForm, Action onComplete)
    {
        _isPlaying = true;
        panelRoot.SetActive(true);
        panelCanvasGroup.alpha = 0f;

        string oldName = beast.baseBeast.beastName;
        string newName = targetForm.beastName;

        // Thiết lập ban đầu
        titleText.text = $"Cái gì thế này? <color=#FFD700>{oldName}</color> đang có biến đổi...!";
        messageText.text = "";
        continuePromptText.gameObject.SetActive(false);

        beastImage.sprite = beast.baseBeast.frontSprite;
        beastImage.color = Color.white;
        whiteSilhouetteImage.sprite = beast.baseBeast.frontSprite;
        whiteSilhouetteImage.color = new Color(1f, 1f, 1f, 0f);
        fullScreenFlash.color = new Color(1f, 1f, 1f, 0f);

        Transform centerTr = beastImage.transform.parent;
        centerTr.localScale = Vector3.one;

        // Fade in Panel
        float elapsed = 0f;
        while (elapsed < 0.6f)
        {
            elapsed += Time.unscaledDeltaTime;
            panelCanvasGroup.alpha = Mathf.Clamp01(elapsed / 0.6f);
            yield return null;
        }
        panelCanvasGroup.alpha = 1f;

        yield return new WaitForSecondsRealtime(0.8f);

        titleText.text = $"<color=#FFD700>{oldName}</color> đang tiến hóa...!";

        // ── GIAI ĐOẠN 1: NHẤP NHÁY TĂNG DẦN (BLINKS ACCELERATION) ──────────────
        // Nhịp độ nhấp nháy từ chậm đến cực nhanh trong khoảng ~3.5 giây
        float totalBlinkDuration = 3.5f;
        float blinkElapsed = 0f;
        float currentInterval = 0.35f;
        bool isSilhouette = false;

        while (blinkElapsed < totalBlinkDuration)
        {
            isSilhouette = !isSilhouette;
            whiteSilhouetteImage.color = new Color(1f, 1f, 1f, isSilhouette ? 1f : 0f);

            // Nhịp thở nhẹ của thú khi đang tiến hóa
            float scaleProgress = blinkElapsed / totalBlinkDuration;
            float currentScale = 1f + Mathf.Sin(blinkElapsed * 10f) * (0.05f + scaleProgress * 0.15f);
            centerTr.localScale = new Vector3(currentScale, currentScale, 1f);

            // Xoay nhẹ hào quang
            if (glowAuraImage != null)
            {
                glowAuraImage.transform.Rotate(Vector3.forward, 90f * Time.unscaledDeltaTime);
            }

            // Tần số nhấp nháy tăng tốc nhanh dần
            currentInterval = Mathf.Lerp(0.35f, 0.04f, scaleProgress);
            yield return new WaitForSecondsRealtime(currentInterval);
            blinkElapsed += currentInterval;
        }

        // ── GIAI ĐOẠN 2: BÙNG SÁNG CHÓI LÒA (FULLSCREEN FLASH BURST) ──────────
        elapsed = 0f;
        while (elapsed < 0.3f)
        {
            elapsed += Time.unscaledDeltaTime;
            float a = Mathf.Clamp01(elapsed / 0.3f);
            fullScreenFlash.color = new Color(1f, 1f, 1f, a);
            yield return null;
        }
        fullScreenFlash.color = Color.white;

        // ── GIAI ĐOẠN 3: THỰC THI BIẾN ĐỔI CHÍNH THỨC ─────────────────────────
        beast.Evolve(targetForm);

        // Đổi sang sprite mới
        beastImage.sprite = targetForm.frontSprite;
        whiteSilhouetteImage.sprite = targetForm.frontSprite;
        whiteSilhouetteImage.color = new Color(1f, 1f, 1f, 0f);
        centerTr.localScale = Vector3.one * 1.25f; // Bật phóng to nhẹ khi vừa biến hình

        yield return new WaitForSecondsRealtime(0.2f);

        // ── GIAI ĐOẠN 4: HÉ LỘ HÌNH THÁI MỚI & ĂN MỪNG (REVEAL & SPARKLES) ────
        elapsed = 0f;
        while (elapsed < 0.8f)
        {
            elapsed += Time.unscaledDeltaTime;
            float a = 1f - Mathf.Clamp01(elapsed / 0.8f);
            fullScreenFlash.color = new Color(1f, 1f, 1f, a);

            // Co nhẹ về kích thước chuẩn
            centerTr.localScale = Vector3.Lerp(Vector3.one * 1.25f, Vector3.one, elapsed / 0.8f);
            yield return null;
        }
        fullScreenFlash.color = new Color(1f, 1f, 1f, 0f);

        // Hiệu ứng hạt sao lấp lánh quanh dạng mới
        StartCoroutine(SpawnSparklesRoutine(centerTr.position));

        titleText.text = "<color=#00FFAA>★ TIẾN HÓA THÀNH CÔNG! ★</color>";
        messageText.text = $"Chúc mừng! <color=#FFD700>{oldName}</color> đã tiến hóa thành <color=#00FFAA>{newName}</color>!";
        continuePromptText.gameObject.SetActive(true);

        // Chớp nháy nhẹ prompt "Nhấn F để tiếp tục"
        Coroutine promptRoutine = StartCoroutine(PulsePromptRoutine());

        // Chờ người chơi bấm xác nhận
        yield return new WaitForSecondsRealtime(0.5f);
        while (!Input.GetKeyDown(KeyCode.F) && !Input.GetKeyDown(KeyCode.Space) && !Input.GetMouseButtonDown(0))
        {
            yield return null;
        }

        if (promptRoutine != null) StopCoroutine(promptRoutine);

        // ── GIAI ĐOẠN 5: ĐÓNG MÀN HÌNH CUTSCENE ───────────────────────────────
        elapsed = 0f;
        while (elapsed < 0.4f)
        {
            elapsed += Time.unscaledDeltaTime;
            panelCanvasGroup.alpha = 1f - Mathf.Clamp01(elapsed / 0.4f);
            yield return null;
        }

        panelRoot.SetActive(false);
        _isPlaying = false;

        Debug.Log($"<color=green>[EvolutionCutscene]</color> Hoàn tất tiến hóa: {oldName} → {newName}!");
        onComplete?.Invoke();
    }

    private IEnumerator PulsePromptRoutine()
    {
        while (true)
        {
            float alpha = 0.4f + Mathf.PingPong(Time.unscaledTime * 2f, 0.6f);
            continuePromptText.color = new Color(0.9f, 0.9f, 0.9f, alpha);
            yield return null;
        }
    }

    private IEnumerator SpawnSparklesRoutine(Vector3 centerPos)
    {
        if (sparklesContainer == null) yield break;

        // Tạo 16 ngôi sao tia sáng bay bung ra xung quanh
        List<GameObject> sparkles = new List<GameObject>();
        for (int i = 0; i < 16; i++)
        {
            GameObject sp = new GameObject($"Sparkle_{i}");
            sp.transform.SetParent(sparklesContainer, false);
            var rect = sp.AddComponent<RectTransform>();
            rect.sizeDelta = new Vector2(24, 24);
            rect.anchoredPosition = Vector2.zero;

            var img = sp.AddComponent<Image>();
            img.color = Color.Lerp(Color.yellow, Color.cyan, UnityEngine.Random.value);

            float angle = (i / 16f) * Mathf.PI * 2f;
            Vector2 dir = new Vector2(Mathf.Cos(angle), Mathf.Sin(angle));
            float dist = UnityEngine.Random.Range(120f, 220f);

            StartCoroutine(AnimateSingleSparkle(rect, img, dir * dist));
            sparkles.Add(sp);
        }

        yield return new WaitForSecondsRealtime(1.5f);

        foreach (var s in sparkles)
        {
            if (s != null) Destroy(s);
        }
    }

    private IEnumerator AnimateSingleSparkle(RectTransform rect, Image img, Vector2 targetOffset)
    {
        float dur = UnityEngine.Random.Range(0.8f, 1.2f);
        float elapsed = 0f;
        Vector2 startPos = rect.anchoredPosition;

        while (elapsed < dur)
        {
            elapsed += Time.unscaledDeltaTime;
            float t = elapsed / dur;

            rect.anchoredPosition = Vector2.Lerp(startPos, targetOffset, Mathf.SmoothStep(0f, 1f, t));
            rect.localScale = Vector3.one * (1f - t);
            img.color = new Color(img.color.r, img.color.g, img.color.b, 1f - t);
            yield return null;
        }
    }
}
